#!/bin/bash

mpc stop
amixer -M set Master 128 > /dev/null 2>&1
aplay /root/coax1.wav
amixer -M set Master $(cat /root/vol)% > /dev/null 2>&1

mpc clear
mpc add alsa://hw:0
mpc play

i2cset -y 1 17 1 0x7a
i2cset -y 1 17 3 0x43

echo coaxial 1 > /root/input
